export const TC={Normal:"#C6C6A7",Fire:"#FF8A5B",Water:"#6CB6FF",Electric:"#FFD23F",Grass:"#7BD88F",Ice:"#9FE7F0",Fighting:"#E4685F",Poison:"#C07AD8",Ground:"#E0C068",Flying:"#A9B8FF",Psychic:"#FF7EB0",Bug:"#B5D13A",Rock:"#CDB86B",Ghost:"#9B7BFF",Dragon:"#8D7BFF",Dark:"#9A8478",Steel:"#B8C4D8",Fairy:"#FFAAD4"};
export const RAW=[
["Bulbasaur",1,"Grass/Poison","wa2 br2","Steady, kind and quietly growing into something big."],
["Charmander",4,"Fire","hu3 wa1","Small flame, big plans. You are just getting started."],
["Squirtle",7,"Water","wi2 wa2 ch1","Cool, loyal and always with a squad."],
["Charizard",6,"Fire/Flying","hu3 dr2 ch1","Loud ambition and big flames. You post like someone already building the thing."],
["Butterfree",12,"Bug/Flying","wa3 wi1","Soft, graceful and a favourite to see in the timeline."],
["Pikachu",25,"Electric","wa3 ch2 wi1","Bright, friendly and a little too energetic. People follow you for the good vibes and stay for the sparks."],
["Raichu",26,"Electric","hu2 ch2 wa1","Pikachu with a plan and a bigger voltage."],
["Clefairy",35,"Fairy","wa3 wi1 dr1","Sweet, dreamy and a bit of a moon child."],
["Ninetales",38,"Fire","wi3 dr1 br1","Elegant, a little mysterious and hard to impress."],
["Jigglypuff",39,"Normal/Fairy","dr3 ch2 wa1","Main character energy. If nobody is listening, you will simply post again."],
["Zubat",41,"Poison/Flying","ch3 wi1","Up at all hours and full of random noise."],
["Vileplume",45,"Grass/Poison","wa2 dr2","Looks sweet, comes with opinions."],
["Meowth",52,"Normal","hu3 wi2","Street smart with an eye on the money. You spot an angle before anyone else is awake."],
["Persian",53,"Normal","wi2 hu2 dr1","Polished, picky and always on brand."],
["Psyduck",54,"Water","ch3 wi2 wa1","Gloriously confused and somehow everyone relates. Chaos is your brand."],
["Growlithe",58,"Fire","wa3 hu1","Loyal to the core and first to show up."],
["Arcanine",59,"Fire","hu3 wa2","Fast, loyal and built to chase the goal."],
["Poliwhirl",61,"Water","wi2 ch2 wa1","Goes with the flow and keeps everyone entertained."],
["Abra",63,"Psychic","br2 wi1","Says little, thinks a lot, then disappears."],
["Alakazam",65,"Psychic","br3 wi3","Big brain, dry humor. You explain things and make the room laugh while doing it."],
["Machamp",68,"Fighting","hu3 br1","Four arms, one schedule, zero days off."],
["Gastly",92,"Ghost/Poison","wi2 ch2 dr1","Turns up in the replies when you least expect it."],
["Gengar",94,"Ghost/Poison","wi3 ch2 dr2","Sharp, sly and always one joke ahead. Your replies are why people check the comments."],
["Onix",95,"Rock/Ground","hu1 dr1","Solid, unshakeable and slow to react."],
["Hypno",97,"Psychic","br2 wi2 dr1","Slow-burn takes that make people stop scrolling."],
["Voltorb",100,"Electric","ch3 dr1","Looks harmless and goes off without warning."],
["Exeggutor",103,"Grass/Psychic","ch2 br2 wi1","Big brain energy in several directions at once."],
["Cubone",104,"Ground","wa3 dr1","Quiet, sentimental and carrying more than you show."],
["Lickitung",108,"Normal","ch2 wi1 wa1","Extra, curious and into everything."],
["Koffing",109,"Poison","ch2 dr2","A small cloud of hot takes."],
["Chansey",113,"Normal","wa3","Looks after everyone, probably too much."],
["Kangaskhan",115,"Normal","wa3 hu2","Protective, capable and carrying a whole crew."],
["Mr. Mime",122,"Psychic/Fairy","wi3 br1 ch1","Plays the character perfectly and never breaks."],
["Scyther",123,"Bug/Flying","hu2 dr2 wi1","Sharp, fast and out of patience for nonsense."],
["Jynx",124,"Ice/Psychic","dr2 wi2 ch1","Loud, stylish and always the centre of the room."],
["Magikarp",129,"Water","ch2 hu2","Splashing around now, a dragon in the making."],
["Gyarados",130,"Water/Flying","dr3 hu2 ch1","The glow-up nobody saw coming, and it is fierce."],
["Lapras",131,"Water/Ice","wa3 br1","Gentle, a good listener and a safe ride home."],
["Porygon",137,"Normal","br3 ch1","Built for data, a bit glitchy and deeply logical."],
["Eevee",133,"Normal","wa2 br1 wi1 hu1","Adaptable and full of potential. You can evolve in any direction, and your feed shows it."],
["Snorlax",143,"Normal","wa1","Calm, low-key and unbothered. You post rarely, and the internet waits."],
["Dragonite",149,"Dragon/Flying","wa3 hu2","Big heart, big wings and delivers on time."],
["Mewtwo",150,"Psychic","br3 dr2 hu2","Intense, analytical and built different. You do not post often, but when you do it lands like a verdict."],
["Mew",151,"Psychic","ch2 wi2 wa2 hu1","Curious, playful and impossible to pin down."],
["Togepi",175,"Fairy","wa3 ch1","Pure good vibes in a tiny package."],
["Ampharos",181,"Electric","wa2 br2 hu1","A guiding light people look up to."],
["Marill",183,"Water/Fairy","wa3 ch1","Bouncy, friendly and hard to dislike."],
["Sudowoodo",185,"Rock","ch2 wi2 dr1","Pretending to be a tree and not fooling anyone."],
["Espeon",196,"Psychic","br3 wi1 wa1","Calm, perceptive and a step ahead of the group chat."],
["Umbreon",197,"Dark","wi2 br2 dr1","Night owl, cool head, sharp one-liners."],
["Slowking",199,"Water/Psychic","br3 wi2","Takes a while, then says the smartest thing in the room."],
["Wobbuffet",202,"Psychic","wi2 dr1 wa1","Never starts it, never backs down either."],
["Scizor",212,"Bug/Steel","hu3 dr1","Precise, polished and focused on the win."],
["Tyranitar",248,"Rock/Dark","dr3 hu2","Big presence and bigger opinions."],
["Lugia",249,"Psychic/Flying","br2 wa2 wi1","Calm, rare and rarely seen online."],
["Celebi",251,"Psychic/Grass","wa2 wi2 br1","A gentle time traveller who brings good news."],
["Blaziken",257,"Fire/Fighting","hu3 dr1 ch1","Always training, always kicking higher."],
["Mudkip",258,"Water","ch2 wa2 wi1","Chill, cute and a meme waiting to happen."],
["Gardevoir",282,"Psychic/Fairy","wa3 br1 wi1","Feels everything for everyone and protects the people it loves."],
["Sableye",302,"Dark/Ghost","wi2 ch2 dr1","Shiny taste and chaotic mischief."],
["Mawile",303,"Steel/Fairy","wi2 dr2 wa1","Sweet face, jaws in the back."],
["Aggron",306,"Steel/Rock","hu2 dr1 wa1","Protective, tough and fiercely loyal to its patch."],
["Torkoal",324,"Fire","br1 wa1 dr1","Slow, steady and lets the steam out in puffs."],
["Milotic",350,"Water","wa2 wi2 hu1","Graceful, admired and calming to be around."],
["Absol",359,"Dark","dr3 br1","The one who warns everyone and gets blamed for it."],
["Salamence",373,"Dragon/Flying","ch2 hu2 dr2","Dream big, fly fast, land loudly."],
["Metagross",376,"Steel/Psychic","br3 hu2","Four brains and calculates everything."],
["Rayquaza",384,"Dragon/Flying","dr2 hu2 br1","Rules the sky from a very high post."],
["Infernape",392,"Fire/Fighting","hu2 ch3","Fast, loud and always up to something."],
["Piplup",393,"Water","hu2 wa1 dr1","Proud, small and absolutely sure of itself."],
["Luxray",405,"Electric","br2 hu2 dr1","Sees through everything and acts quickly."],
["Garchomp",445,"Dragon/Ground","hu3 ch1 dr1","Pure speed and ambition, no time for small talk."],
["Lucario",448,"Fighting/Steel","hu2 br2 wa2","Disciplined, loyal and quietly powerful. You read the energy and then act."],
["Weavile",461,"Dark/Ice","wi3 dr1 hu1","Sharp, sly and always a plot twist."],
["Togekiss",468,"Fairy/Flying","wa3 wi1 br1","Spreads good luck wherever it lands."],
["Gallade",475,"Psychic/Fighting","br2 wa2 hu1","Thoughtful, chivalrous and quick to defend friends."],
["Rotom",479,"Electric/Ghost","ch3 wi2","Possesses every device and every group chat."],
["Excadrill",530,"Ground/Steel","hu3 ch1","Digs in and drills straight to the result."],
["Zorua",570,"Dark","wi2 ch2","Master of disguise and a little prankster."],
["Zoroark",571,"Dark","wi3 dr2 ch1","Plays tricks, and the mask is the brand."],
["Chandelure",609,"Ghost/Fire","dr2 wi2 br1","Elegant, haunting and very good at slow burns."],
["Haxorus",612,"Dragon","hu2 dr2","Direct and fierce, cuts through the noise."],
["Fennekin",653,"Fire","wa2 wi1 hu1","Warm, curious and still finding its flame."],
["Greninja",658,"Water/Dark","wi3 hu2 dr1","Fast and precise, strikes with perfect timing."],
["Pancham",674,"Fighting","dr2 ch2 hu1","Tough-guy act, soft inside."],
["Sylveon",700,"Fairy","wa3 wi1 br1","Ribbons, kindness and a tender touch."],
["Hawlucha",701,"Fighting/Flying","ch2 hu2 dr1","Big entrance, bigger pose."],
["Goodra",706,"Dragon","wa3 ch1 wi1","Soft, slippery and just wants a hug."],
["Rowlet",722,"Grass/Flying","wa2 br1 wi1","Sleepy, thoughtful and a little daydreamy."],
["Decidueye",724,"Grass/Ghost","br2 hu2 wi1","Silent, aim-true and does not miss."],
["Lycanroc",745,"Rock","hu2 wa2 dr1","Loyal, fiery and full of pack energy."],
["Toxapex",748,"Poison/Water","dr2 br1 wa1","Prickly defences, caring underneath."],
["Bewear",760,"Normal/Fighting","wa2 ch2","Gives bear hugs that might be a lot."],
["Mimikyu",778,"Ghost/Fairy","wa2 wi2 dr1","Wears the costume so people like you, secretly sweet."],
["Cinderace",815,"Fire","hu3 ch1","Always warming up for the next big match."],
["Corviknight",823,"Flying/Steel","hu2 br2","Efficient, reliable and always on schedule."],
["Wooloo",831,"Normal","wa2 ch2","Fluffy chaos that rolls in unannounced."],
["Morpeko",877,"Electric/Dark","dr2 ch2 wi1","Hangry and hilarious in equal measure."],
["Dragapult",887,"Dragon/Ghost","hu2 wi2 ch1","Fast, spooky and always launching something."],
["Sprigatito",906,"Grass","wa2 wi2","Cute, sassy and knows it."]
];
export const ROSTER=Object.fromEntries(RAW.map(r=>{const t=r[2].split("/");return[r[0],{n:r[0],dex:r[1],t,c:TC[t[0]]}]}));
export const NAMES={chaos:"Chaos",warmth:"Warmth",wit:"Wit",hustle:"Hustle",brain:"Brains",drama:"Drama"};
export const COL={chaos:"#FF9F1C",warmth:"#FF4F6D",wit:"#7B5CFF",hustle:"#12A594",brain:"#2D9CDB",drama:"#C2185B"};
